### ISSUE TITLE
Problem: Guzzle/Pool with kevin-rob/guzzle-cache-middleware - Invoking the wait callback did not resolve the promise

### ISSUE THREAD

**Issue by kdefives** [guzzle/guzzle#2822]
**Guzzle version(s) affected**: 7.2.0
**PHP version**: 7.4.12
**cURL version**: 7.64.0

Project using Symfony 5.1.8

Versions info:
```bash
root@7a917597f9c1:/var/www# composer show | grep guzzle
guzzlehttp/guzzle                     7.2.0     Guzzle is a PHP HTTP client library
guzzlehttp/promises                   1.4.0     Guzzle promises library
guzzlehttp/psr7                       1.7.0     PSR-7 message implementation that also provides common utility methods
kevinrob/guzzle-cache-middleware      v3.3.1    A HTTP/1.1 Cache for Guzzle 6. It's a simple Middleware to be added in the HandlerStack. (RFC 7234)
spatie/guzzle-rate-limiter-middleware 2.0.0     A rate limiter for Guzzle
```

**Description**  

Using https://github.com/Kevinrob/guzzle-cache-middleware for caching, the error below occurs when we try to do asynchronous request using Pool if the cache is used.

```bash
request.CRITICAL: Uncaught PHP Exception GuzzleHttp\Promise\RejectionException: "The promise was rejected with reason: Inv
oking the wait callback did not resolve the promise" at /var/www/vendor/guzzlehttp/promises/src/Create.php line 62 {"exception":"[object] (GuzzleHttp\\Promis
e\\RejectionException(code: 0): The promise was rejected with reason: Invoking the wait callback did not resolve the promise at /var/www/vendor/guzzlehttp/pr
omises/src/Create.php:62)"} []
```

Part of stacktrace:
```bash
GuzzleHttp\Promise\RejectionException:
The promise was rejected with reason: Invoking the wait callback did not resolve the promise

  at vendor/guzzlehttp/promises/src/Create.php:62
  at GuzzleHttp\Promise\Create::exceptionFor('Invoking the wait callback did not resolve the promise')
     (vendor/guzzlehttp/promises/src/Promise.php:72)
  at GuzzleHttp\Promise\Promise->wait()
```

**How to reproduce**  

**Step 1:**
Let's execute this code

```php
private function test(){

        $productIdsToCheck = new ArrayCollection([1,2,3,4,100,6,7,8,9,99]);

        // Create request function
        $requests = function ($productIdsToCheck)
        {
            foreach ($productIdsToCheck as $key => $productId)
            {
                yield new Request(
                    'GET',
                    'https://httpbin.org/'.$productId
                );
            }
        };

        // Create the pool using $request function
        $pool = new Pool($this->httpClient, $requests($productIdsToCheck), [
            'concurrency' => 5,
            'fulfilled' => function (Response $response, $index)
            {
                // this is delivered each successful response
            },
            'rejected' => function (RequestException $reason, $index)
            {
            },
        ]);

        // Initiate the transfers and create a promise
        $promise = $pool->promise();

        // Force the pool of requests to complete.
        $promise->wait();
    }
```

Everything is ok the first time.

**Step 2:**
Now, just change the value from 100 to 10 into the ArrayCollection $productIdsToCheck variable and re-execute the same code
```php
private function test(){

        $productIdsToCheck = new ArrayCollection([1,2,3,4,10,6,7,8,9,99]);

        // Create request function
        $requests = function ($productIdsToCheck)
        {
            foreach ($productIdsToCheck as $key => $productId)
            {
                yield new Request(
                    'GET',
                    'https://httpbin.org/'.$productId
                );
            }
        };

        // Create the pool using $request function
        $pool = new Pool($this->httpClient, $requests($productIdsToCheck), [
            'concurrency' => 5,
            'fulfilled' => function (Response $response, $index)
            {
                // this is delivered each successful response
            },
            'rejected' => function (RequestException $reason, $index)
            {
            },
        ]);

        // Initiate the transfers and create a promise
        $promise = $pool->promise();

        // Force the pool of requests to complete.
        $promise->wait();
    }
```

**And the error message appears:**
```bash
The promise was rejected with reason: Invoking the wait callback did not resolve the promise
```

Dependencies injection as i am using symfony 5.1.8:
```yaml
#services.yaml

services:
_defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $httpClient: '@http_api_client'

        Kevinrob\GuzzleCache\Storage\Psr6CacheStorage:
                class: Kevinrob\GuzzleCache\Storage\Psr6CacheStorage
                arguments: [ '@cache.app' ]

            Kevinrob\GuzzleCache\Strategy\GreedyCacheStrategy:
                class: Kevinrob\GuzzleCache\Strategy\GreedyCacheStrategy
                arguments: [ '@Kevinrob\GuzzleCache\Storage\Psr6CacheStorage', '3600' ]

            Kevinrob\GuzzleCache\CacheMiddleware:
                class: Kevinrob\GuzzleCache\CacheMiddleware
                arguments: [ '@Kevinrob\GuzzleCache\Strategy\GreedyCacheStrategy' ]

        GuzzleHttp\HandlerStack:
                class: GuzzleHttp\HandlerStack
                factory: [ 'GuzzleHttp\HandlerStack', create ]
                calls:
                    - [ push, [ '@log_middleware', 'log' ] ]
                    - [ push, [ '@Kevinrob\GuzzleCache\CacheMiddleware', 'cache' ] ]
                    - [ push, [ '@Spatie\GuzzleRateLimiterMiddleware\RateLimiterMiddleware', 'rate-limit' ] ]

        http_api_client_
                class: GuzzleHttp\Client
                arguments:
                    - handler: '@GuzzleHttp\HandlerStack'
```

**Possible Solution**  

Do not use Pool (asynchronous request) or do not use https://github.com/Kevinrob/guzzle-cache-middleware/issues
**No real workaround found**

**Additional context**  

**Info 1** : If i remove the cache feature by commenting  the line   - [ push, [ '@Kevinrob\GuzzleCache\CacheMiddleware', 'cache' ] ] ,  then everything woks fine.
If you re-enable cache feature, the problem appears again. Seems linked to the cache.

**Info 2**: I tested different type of cache (flysystem, doctrinecache and psr6) with GreedyCacheStrategy. Same issue for both. I cannot test with PrivateCacheStrategy because in my use case the cache do not cache correctly with that strategy. But it seems to confirm that the problem appears only when the cache is used.

**Info 3:** Same issue with Guzzle6

I will added more comments to this issue if I found more info to help for debugging.
