### ISSUE TITLE
Provide alternatives to getConfig()

### ISSUE THREAD

**Issue by alexislefebvre** [guzzle/guzzle#3114]
**Description**
In #2516, `getConfig()` was deprecated, but no replacement was suggested.

**Example**

We use https://packagist.org/packages/eightpoints/guzzle-bundle to use Guzzle in a Symfony project, with this config:

```yaml
# config/packages/eight_points_guzzle.yaml
eight_points_guzzle:
    clients:
        example_api:
            base_url: "https://api.example.com/"
            options:
                timeout: 30
                http_errors: true
                headers:
                    User-Agent: "EightPointsGuzzleBundle/v7"
                    Content-Type: 'application/json'
                    TokenID: '%example_api_key%'
            plugin: null
```

The method that use Guzzle can return `null` early if no key is provided for this client, so that we can enable or disable the calls to the external API by changing the value of `%example_api_key%` in our different environments.

```php
# src/ExampleClient.php

class ExampleClient
{
    public function __construct(
        private readonly \GuzzleHttp\Client $client,
    ) {
    }

    private function call(): ?array
    {
        if (!$this->client->getConfig()['headers']['TokenID']) {
            return null;
        }
        
        // …

        // the call to Guzzle is done here
        return json_decode(
            $this->client->post($uri, $parameters)->getBody(),
            true, 512, JSON_THROW_ON_ERROR
        );
    }
}
```

If `getConfig()` is removed in Guzzle 8, we won't be able to access to the config and disable these calls.

We could pass `%example_api_key%` to do the same thing but I think that it would be nice to rely only on the `$client` that already contain this value.

**Additional context**

Idea: add `getHeaders()` or something like `getHeader('TokenID')`, etc. to allow to access to the values that are accessible through `getConfig()` today with Guzzle 7.

See also #2514
